name: Hide Sensitive Information
run-name: ${{ github.actor }} is learning GitHub Actions
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: echo a secret
        run: bb="your secret token is ${{secrets.TC_SECRET}}";echo $bb

