name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_php_script:
    runs-on: [self-hosted, linux] 

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Run PHP script
      run: |
        msg="${{ github.event.head_commit.message }}"
        php test.php

  deploy:
    runs-on: ubuntu-latest
    needs: run_php_script
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.SPL_SERVER_HOSTNAME }}
        username: ${{ secrets.SPL_SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/var/www/html"

    - name: Restart Apache
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SPL_SERVER_HOSTNAME }}
        username: ${{ secrets.SPL_SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: sudo systemctl restart apache2
